---
#----------------------------------mysql-ansible全局配置文件---------------------
# section 1 #mysql-ansible所在的目录
mtls_base_dir: /usr/local/mysql-ansible/
#           #mysqltool自带的各类软件的安装文件所在路径(相对路径)
mtls_packages: deploy/packages/
#           #mysqltool自带的python脚本、下发到被控主机时所保存的路径
mtls_client_base_dir: /usr/local/


#  section 2  #mysql-ansible自带的各类软件安装文件 的全名、设置这些变量的作用是方便版本共存、mysql不在这里设置是因为
#             #mysql的安装包太大了，mysql-ansible并没有把它打包进来         
mtls_apr: apr-1.6.2.tar.gz
mtls_apr_util: apr-util-1.6.0.tar.gz
mtls_httpd: httpd-2.4.28.tar.gz
#mtls_php: php-5.6.31.tar.gz
#mtls_zabbix: zabbix-3.4.3.tar.gz
mtls_zabbix: zabbix-4.0.0.tar.gz
mtls_python: python-3.6.2.tar.xz
mtls_mysql_connector_python: mysql_connector_python-8.0.12-cp36-cp36m-manylinux1_x86_64.whl
#mtls_mycat: mycat-server-1.6.5-linux.tar.gz
#mtls_mha_node: mhanode.tar.gz
#mtls_mha_manager: mhamanager.tar.gz
mtls_git: git-2.9.5.tar.gz
mtls_nginx: nginx-1.13.7.tar.gz
mtls_sysbench: sysbench-1.1.0.tar.gz
mtls_meb: meb-4.1.0-linux-glibc2.5-x86-64bit.tar.gz
mtls_xtrb: percona-xtrabackup-2.4.9-Linux-x86_64.tar.gz
mtls_mysqlclient: mysqlclient-1.3.12.tar.gz
mtls_pytz: pytz-2018.4.tar.gz
mtls_django: django-2.0.4.tar.gz
mtls_uwsgi: uwsgi-2.0.17.tar.gz

#mysql与php-5.6.x 是否要同时安装在一台主机上、如果是就要把这个设置成yes、以为php导出mysqclient_r.so文件
mtls_with_php: 1
#通过ansible在被控机上安装python-3.x的时候，是否自动安装好mysql-connector-python
mtls_with_mysql_conntor_python: 1
#是否给mysql用户加密码
mtls_make_mysql_secure: 1
#
mtls_with_mysql_group_replication: 0
#----------------------------------mysql-ansible全局配置文件---------------------


####
#### mysql 相关的配置
####
# mysql 安装包所在的目录
## MySQL安装包太大，需要直接从官方下载，这里的目录中是空的
mysql_packages_dir: /usr/local/mysql-ansible/deploy/packages/mysql/
#mysql 安装包的名字
mysql_version: 57
mysql_server_package: mysql-community-server-5.7.29-1.el7.x86_64.rpm
mysql_client_package: mysql-community-client-5.7.29-1.el7.x86_64.rpm
mysql_common_package: mysql-community-common-5.7.29-1.el7.x86_64.rpm
mysql_libs_package: mysql-community-libs-5.7.29-1.el7.x86_64.rpm
mysql_libs_compact_package: mysql-community-libs-compat-5.7.29-1.el7.x86_64.rpm
mysql_devel_package: mysql-community-devel-5.7.29-1.el7.x86_64.rpm
#linux 系统级别mysql用户相关信息
mysql_user: mysql
mysql_group: mysql
mysql_user_uid: 3306
mysql_user_gid: 3306
#mysql 安装目录
#mysql_base_dir: /usr/local/mysql/
mysql_data_dir_base: /usr/local/mysql
mysql_port: 3306
mysql_root_password: i528jc4QqxGm0J88
#mysql_zabbix_password: mtls
mysql_repl_user: repl
mysql_repl_password: i528jc4QqxGm0J88
#mysql_mha_user: mha
#mysql_mha_password: mtls0352
#mysql_app_user: appuser
#mysql_app_password: mtls0352
mysql_monitor_user: monitor
mysql_monitor_password: i528jc4QqxGm0J88
mysql_backup_user: backup
mysql_backup_password: i528jc4QqxGm0J88
#mysql 配置文件模版
mysql_binlog_format: row
mysql_innodb_log_files_in_group: 4
mysql_innodb_log_file_size: 512M
mysql_innodb_log_buffer_size: 64M
mysql_innodb_open_files: 65535
mysql_max_connections: 3000
mysql_thread_cache_size: 256
mysql_sync_binlog: 1
mysql_binlog_cache_size: 64K
mysql_innodb_online_alter_log_max_size: 128M
mysql_performance_schema: 'on'
use_write_set: 1

#mysql 

####
#### zabbix 相关的配置
#####
#zabbix_server_ip: 172.16.192.100 

#### proxysql 相关配置
proxysql_package_dir: /usr/local/mysql-ansible/deploy/packages/proxysql
proxysql_package: proxysql-2.0.12-1-centos7.x86_64.rpm
proxysql_gnutls_package: gnutls-3.3.29-9.el7_6.x86_64.rpm
proxysql_nettle_package: nettle-2.7.1-8.el7.x86_64.rpm
proxysql_trousers_package: trousers-0.3.14-2.el7.x86_64.rpm
proxysql_version: 2.0.12


#### xtrabackup相关配置
xtrabackup_packages_dir: /usr/local/mysql-ansible/deploy/packages/xtrabackup/
xtrabackup_package: percona-xtrabackup-24-2.4.20-1.el7.x86_64.rpm
xtrabackup_qpress_package: qpress-11-1.el7.x86_64.rpm
xtrabackup_libev_package: libev-4.15-7.el7.x86_64.rpm
xtrabackup_perl_data_dumper_package: perl-Data-Dumper-2.145-3.el7.x86_64.rpm
xtrabackup_perl_compress_bzip_package: perl-Compress-Raw-Bzip2-2.061-3.el7.x86_64.rpm
xtrabackup_perl_compress_zlib_package: perl-Compress-Raw-Zlib-2.061-4.el7.x86_64.rpm
xtrabackup_perl_bdb_mysql_package: perl-DBD-MySQL-4.023-6.el7.x86_64.rpm
xtrabackup_perl_dbi_package: perl-DBI-1.627-4.el7.x86_64.rpm
xtrabackup_perl_digest_package: perl-Digest-1.17-245.el7.noarch.rpm
xtrabackup_perl_digest_md5_package: perl-Digest-MD5-2.52-3.el7.x86_64.rpm
xtrabackup_perl_io_compress_package: perl-IO-Compress-2.061-2.el7.noarch.rpm
xtrabackup_perl_net_daemon_package: perl-Net-Daemon-0.48-5.el7.noarch.rpm
xtrabackup_perl_plrpc_package: perl-PlRPC-0.2020-14.el7.noarch.rpm

### sysbench相关配置
sysbench_packages_dir: /usr/local/mysql-ansible/deploy/packages/sysbench/
sysbench_pgsql_lib_package: postgresql-libs-9.2.24-4.el7_8.x86_64.rpm
sysbench_package: sysbench-1.0.20-1.el7.x86_64.rpm

### percona toolkit 相关配置
perconatoolkit_packages_dir: /usr/local/mysql-ansible/deploy/packages/perconatoolkit/
perconatoolkit_package: percona-toolkit-3.2.0-1.el7.x86_64.rpm
pt_perl_compress_bzip: perl-Compress-Raw-Bzip2-2.061-3.el7.x86_64.rpm
pt_perl_compress_zlib: perl-Compress-Raw-Zlib-2.061-4.el7.x86_64.rpm
pt_perl_data_dumper: perl-Data-Dumper-2.145-3.el7.x86_64.rpm
pt_perl_dbd_mysql: perl-DBD-MySQL-4.023-6.el7.x86_64.rpm
pt_perl_dbi: perl-DBI-1.627-4.el7.x86_64.rpm
pt_perl_digest: perl-Digest-1.17-245.el7.noarch.rpm
pt_perl_digest_md5: perl-Digest-MD5-2.52-3.el7.x86_64.rpm
pt_perl_io_compress: perl-IO-Compress-2.061-2.el7.noarch.rpm
pt_perl_io_socket: perl-IO-Socket-IP-0.21-5.el7.noarch.rpm
pt_perl_io_socket_ssl: perl-IO-Socket-SSL-1.94-7.el7.noarch.rpm
pt_perl_miozilla_ca: perl-Mozilla-CA-20130114-5.el7.noarch.rpm
pt_perl_net_daemon: perl-Net-Daemon-0.48-5.el7.noarch.rpm
pt_perl_net_libidn: perl-Net-LibIDN-0.12-15.el7.x86_64.rpm
pt_perl_net_ssleay: perl-Net-SSLeay-1.55-6.el7.x86_64.rpm
pt_perl_plrpc: perl-PlRPC-0.2020-14.el7.noarch.rpm
pt_perl_termkey: perl-TermReadKey-2.30-20.el7.x86_64.rpm
pt_maria_lib: mysql-community-libs-5.7.29-1.el7.x86_64.rpm
pt_libv_package: libev-4.15-7.el7.x86_64.rpm


### mydumper 相关配置
mydumper_package_dir: /usr/local/mysql-ansible/deploy/packages/mydumper/
mydumper_package: mydumper-0.9.5-2.el7.x86_64.rpm
