---
 - hosts: single
   remote_user: root
   become_user: yes
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: prepare hostname
      import_tasks: common/prepare_hostname.yaml

    - name: remove mariadb
      import_tasks: common/uninstall_maria.yaml
    
    - name: stop selinux & firewall
      import_tasks: common/stop_selinux.yaml

    - name: create user and config file
      import_tasks: common/create_user_and_config_file.yaml


    - name: install mysql to /usr/local/mysql
      import_tasks: common/install_mysql.yaml

    - name: init mysql datadir
      import_tasks: common/initialize_mysql_datadir.yaml

    - name: config mysql service and start mysql
      import_tasks: common/config_mysql_service_and_start_mysql.yaml

    - name: sleep 5 seconds
      shell: sleep 5

    - name: make mysql secure
      import_tasks: common/make_mysql_security.yaml
...
