---
 - hosts: mgr
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
   tasks:
    - name: stop mysql-service in rhel-7.x
      when: ansible_distribution_major_version == "7"
      systemd: 
       name: mysqld
       state: stopped
      ignore_errors: yes

    - name: delete mysql user
      user:
       name: "{{mysql_user}}"
       remove: yes
       state: absent
      ignore_errors: yes

    - name: remove mysql package
      yum: 
       name: mysql-community-* 
       state: absent

    - name: remove data file
      file: 
       path: "{{mysql_data_dir_base}}"
       state: absent
...
