---
 - hosts: single
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
   tasks:

    - name: stop mysql service 
      when: ansible_distribution_major_version == "7"
      systemd:
       name: mysql
       state: stopped
       daemon_reload: yes
    
    - name: backup config file
      shell: cp /etc/my.cnf /tmp/my.cnf

    - name: remove mysql package
      yum:
        name:  mysql-community*
        state: absent

    - name: install new version
      import_tasks: common/install_mysql.yaml

    - name: recover old config file
      shell: cp /tmp/my.cnf /etc/my.cnf
    
    - name: start mysql service
      when: ansible_distribution_major_version == "7"
      systemd:
       name: mysqld
       state: started
       daemon_reload: yes
           
    - name: remove /tmp/my.cnf
      file:
        dest: /tmp/my.cnf
        state: absent   
