---
  - name: config variables
    proxysql_global_variables:
     login_user: 'admin'
     login_password: 'admin'
     variable: 'mysql-max_connections'
     value: 4096

  - name: config servers
    proxysql_backend_servers:
     hostgroup_id: 10
     login_user: 'admin'
     login_password: 'admin'
     hostname: '{{ item.node }}'
     state: present
     load_to_runtime: True
    with_items:
    - { name: 'node1', node: '192.168.1.10'}
    - { name: 'node2', node: '192.168.1.11'}
    - { name: 'node3', node: '192.168.1.12'}

  - name: config variables
    proxysql_global_variables:
     login_user: 'admin'
     login_password: 'admin'
     variable: 'mysql-monitor_username'
     value: monitor

  - name: config variables
    proxysql_global_variables:
     login_user: 'admin'
     login_password: 'admin'
     variable: 'mysql-monitor_password'
     value: '{{ mysql_monitor_password }}'
     load_to_runtime: True

  # - name: config replication
  #   proxysql_replication_hostgroups:
  #     login_user: 'admin'
  #     login_password: 'admin'
  #     writer_hostgroup: 10
  #     reader_hostgroup: 30
  #     state: present
  #     load_to_runtime: True