---
 - hosts: perconatoolkit
   remote_user: root
   become_user: yes
   vars_files:
    - ../../../config.yaml
   tasks:

    - name: uninstall
      yum: 
        name: percona-toolkit-3.2.0-1.el7.x86_64
        state: absent
...
