---
 - hosts: sysbench
   remote_user: root
   become_user: root
   vars_files:
    - ../../../config.yaml
    - vars/sysbench.yaml
   tasks:
    - name: install sysbench
      import_tasks: common/install_sysbench.yaml

