  - name: transfer sql statement to remote
    template:
     src: ../template/config_mysql_group_replication.sql
     dest: /tmp/config_mysql_group_replication.sql

  - name: transfer monitor sql statement to remote
    template:
     src: ../template/addition_to_sys.sql
     dest: /tmp/addition_to_sys.sql


  - name: config mysql group replication
    shell: mysql -hlocalhost -uroot -p{{ mysql_root_password }} -S {{ mysql_data_dir_base }}/mysql.sock  < /tmp/config_mysql_group_replication.sql

  - name: config mysql group replication
    shell: mysql -hlocalhost -uroot -p{{ mysql_root_password }} -S {{ mysql_data_dir_base }}/mysql.sock  < /tmp/addition_to_sys.sql

  - name: remove temp file /tmp/config_mysql_group_replication.sql
    file:
     dest: /tmp/config_mysql_group_replication.sql
     state: absent

  - name: remove temp file /tmp/addition_to_sys.sql
    file:
     dest: /tmp/addition_to_sys.sql
     state: absent

