---
 - name: transfer sleep script to /tmp/
   copy:
    src: ../template/sleep_15.sh
    dest: /tmp/sleep_15.sh

 - name: sleep 5 seconds
   shell: bash /tmp/sleep_15.sh

 - name: remove /tmp/sleep_15.sh
   file:
    dest: /tmp/sleep_15.sh
    state: absent

   
