---
 - name: stransfer sql to remote host
   template:
    src: ../template/stop_group_replication.sql
    dest: /tmp/stop_group_replication.sql

 - name: create replication user on master / start slave on slave
   when:
   shell: mysql -hlocalhost -uroot -p{{ mysql_root_password }} -S {{ mysql_data_dir_base }}/mysql.sock < /tmp/stop_group_replication.sql

 - name: clear temp file tmp/stop_group_replication.sql
   file:
    dest: tmp/stop_group_replication.sql
    state: absent
